name: Production

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Install VPN
        run: |
          sudo apt-get update -vvv
          sudo apt-get --assume-yes --no-install-recommends install openvpn  
      
      - name: Start VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: ./github/vpn/config.ovpn
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}

      - name: Start Node
        run: |
          ssh devss@10.90.15.143
          whoami
          killall node
          sudo node dist/main

      # - name: Upload
      #   # env:
      #   #   SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   # run: |
      #   #   ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      #   #   ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      #   #   scp -p 22 -r dist devss@10.90.15.143:.
      #   uses: burnett01/rsync-deployments@5.2.1
      #   with:
      #     switches: -avzr --delete
      #     path: dist/
      #     remote_path: dist/
      #     remote_host: 10.90.15.143
      #     remote_user: devss
      #     remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
