name: Production

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-strict: false

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          scp -p 22 -r dist devss@10.90.15.143:.

      - name: Start Node
        run: |
          ssh devss@10.90.15.143
          whoami
          killall node
          sudo node dist/main
