name: Production

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Setup PPTP
        run: |
          sudo apt-get install pptp-linux
          sudo cp -a .github/etc/. /etc/
          sudo pppd call wars
      
      # - name: Check VPN
      #   timeout-minutes: 1
      #   run: until ping 10.90.15.143; do sleep 2; done

      - name: Upload
        run: scp -r /dist {{ secrets.SSH_USERNAME }}@{{ secrets.SSH_HOST }}:dist
    
      - name: Start Node
        run: |
          ssh {{ secrets.SSH_USERNAME }}@{{ secrets.SSH_HOST }} -vvv
          whoami
          killall node
          sudo node dist/main
        # uses: appleboy/ssh-action@v0.1.6
        # with:
        #   host: ${{ secrets.SSH_HOST }}
        #   username: ${{ secrets.SSH_USERNAME }}
        #   password: ${{ secrets.SSH_PASSWORD }}
        #   script: |
        #     whoami
        #     killall node
        #     sudo node dist/main

      # - name: Kill PPTP
      #   run: sudo poff wars-pptp
