name: Production

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy
    timeout-minutes: 5
    env:
      PORT: 3000
      NODE_ENV: production
      DATABASE_URL: postgres://rjyxjtuowkxnig:af1092ab3911a43ef1324f15ddbbcbb65926ea81a3bc29620f85810da6160b92@ec2-34-253-119-24.eu-west-1.compute.amazonaws.com:5432/de3fb1pkk65f62
      DATABASE_SSL: ""
      JWT_SECRET: distant_distance_satellite
      CLOUDINARY_URL: cloudinary://176525619261476:cOXUW6blKaXL89800PmAK3Umez0@cv-gen-cloud
      MAIL_FROM: curriculum.vitae.team@gmail.com
      SMTP_URL: smtp://curriculum.vitae.team@gmail.com:gymnjxhsmvgdbjxw@smtp.gmail.com:587
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install
        run: yarn --production=false --frozen-lockfile

      - name: Build
        run: nest build

      - name: Upload
        run: scp -r /dist devss@10.90.15.143:/dist

      - name: Stop
        run: ssh devss@10.90.15.143 'killall node'

      - name: Start
        run: ssh devss@10.90.15.143 'node dist/src/main'
