name: Production

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      # sudo touch /etc/ppp/peers/wars-pptp
      # sudo cp .github/vpn/wars-pptp /etc/ppp/peers/wars-pptp
      # sudo pon wars-pptp

      - name: Setup PPTP
        run: |
          sudo apt-get install pptp-linux
          sudo cp -a .github/etc/. /etc/
          sudo pppd call wars
      
      - name: Check VPN
        timeout-minutes: 1
        run: until ping 10.90.15.143; do sleep 2; done

      - name: Start Node
        run: |
          ssh devss@10.90.15.143
          whoami
          killall node
          sudo node dist/main

      # - name: Kill PPTP
      #   run: sudo poff wars-pptp

      # - name: Upload
      #   # env:
      #   #   SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   # run: |
      #   #   ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      #   #   ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      #   #   scp -p 22 -r dist devss@10.90.15.143:.
      #   uses: burnett01/rsync-deployments@5.2.1
      #   with:
      #     switches: -avzr --delete
      #     path: dist/
      #     remote_path: dist/
      #     remote_host: 10.90.15.143
      #     remote_user: devss
      #     remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
