name: Production

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unknown

      # - name: Add to authorized keys
      # run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      # run: ssh-copy-id ${{ secrets.SSH_LOGIN }}

      - name: Stop process
        run: ssh devss@10.90.15.143 -tt -vvv 'killall node'

      - name: Upload
        run: scp -r src .env nest-cli.json package.json tsconfig.* yarn.lock ${{ secrets.SSH_LOGIN }}:cv-node

      - name: Install
        run: ssh -A ${{ secrets.SSH_LOGIN }} 'cd cv-node && yarn --frozen-lockfile'

      - name: Build
        run: ssh -A ${{ secrets.SSH_LOGIN }} 'cd cv-node && yarn build'

      - name: Start
        run: ssh -A ${{ secrets.SSH_LOGIN }} 'sudo node cv-node/dist/main'
