name: Production

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Stop
        run: ssh devss@10.90.15.143 'killall node'

      - name: Upload
        run: scp -r src .env nest-cli.json package.json tsconfig.* yarn.lock devss@10.90.15.143:cv-node

      - name: Install
        run: ssh devss@10.90.15.143 'cd cv-node && yarn --frozen-lockfile'

      - name: Build
        run: ssh devss@10.90.15.143 'cd cv-node && yarn build'

      - name: Start
        run: ssh devss@10.90.15.143 'sudo node cv-node/dist/main'
