name: Production

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Stop process
        run: ssh ${{ secrets.SSH_LOGIN }} 'killall node'

      - name: Upload
        run: scp -r src .env nest-cli.json package.json tsconfig.* yarn.lock ${{ secrets.SSH_LOGIN }}:cv-node

      - name: Install
        run: ssh ${{ secrets.SSH_LOGIN }} 'cd cv-node && yarn --frozen-lockfile'

      - name: Build
        run: ssh ${{ secrets.SSH_LOGIN }} 'cd cv-node && yarn build'

      - name: Start
        run: ssh ${{ secrets.SSH_LOGIN }} 'sudo node cv-node/dist/main'
