name: Production

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Docker environment
        run: |
          cd docker
          touch .env.docker
          echo PORT=${{ secrets.PORT }} >> .env.docker
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env.docker
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.docker
          echo CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }} >> .env.docker
          echo MAIL_FROM=${{ secrets.MAIL_FROM }} >> .env.docker
          echo SMTP_URL=${{ secrets.SMTP_URL }} >> .env.docker

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cv_node:latest
