name: Production

on:
  push:
    branches:
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Create Docker environment
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PORT: ${{ secrets.PORT }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          envkey_MAIL_FROM: ${{ secrets.MAIL_FROM }}
          envkey_SMTP_URL: ${{ secrets.SMTP_URL }}
          directory: docker
          file_name: .env.docker

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cv_node:latest
