name: Production

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Connect to PPTP VPN
        run: |
          sudo apt-get install pptp-linux network-manager-pptp
          echo "{{ secrets.VPN_USERNAME }}      PPTP      {{ secrets.VPN_PASSWORD }}     *" > /etc/ppp/chap-secrets
          echo "pty 'pptp {{ secrets.VPN_ADDRESS }} --nolaunchpppd'
                name wars
                remotename PPTP
                require-mppe-128
                file /etc/ppp/options.pptp
                ipparam pptp-us1" > /etc/ppp/peers/pptp-wars
          vi /etc/ppp/ip-up.d/vpn-traffic
          route add -net 10.0.0.0/8 dev ppp0
          chmod +x /etc/ppp/ip-up.d/vpn-traffic
          pppd call pptp-wars

      - name: Start Node
        run: |
          ssh devss@10.90.15.143
          whoami
          killall node
          sudo node dist/main

      # - name: Upload
      #   # env:
      #   #   SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   # run: |
      #   #   ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      #   #   ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      #   #   scp -p 22 -r dist devss@10.90.15.143:.
      #   uses: burnett01/rsync-deployments@5.2.1
      #   with:
      #     switches: -avzr --delete
      #     path: dist/
      #     remote_path: dist/
      #     remote_host: 10.90.15.143
      #     remote_user: devss
      #     remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
